### ISSUE TITLE
A little help to reproduce the openbox rice

### ISSUE THREAD

**Issue by pierre-rs** [juminai/opendots#1]
Hello!

Sorry to have to ask this, but I'm trying to reproduce your openbox rice and would you happen to be able to tell me which packages would need to be installed on Arch Linux so that I can reproduce your rice correctly?

For example, should I install the `eww` or `eww-x11` package (currently I'm using Gnome on X11)? Would there be any other packages requirements that you would recommend that I install?

Thanks for share your rice!

**Comment by juminai** [comment]
the eww binary is alrady in the bin folder, so dont need to install it.
some packages: 
```
jgmenu dunst pamixer feh playerctl openbox obconf alacritty picom starship xsettingsd picom  xorg xorg-xinit
```
